{{- $component := "worker" -}}
{{- $name := include "efficientai.componentFullname" (dict "root" . "component" $component) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "efficientai.componentLabels" (dict "root" . "component" $component) | nindent 4 }}
spec:
  {{- if not .Values.efficientai.worker.autoscaling.enabled }}
  replicas: {{ .Values.efficientai.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "efficientai.componentSelectorLabels" (dict "root" . "component" $component) | nindent 6 }}
  {{- with .Values.efficientai.worker.deployment.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "efficientai.componentSelectorLabels" (dict "root" . "component" $component) | nindent 8 }}
        {{- with .Values.efficientai.worker.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.efficientai.worker.pod.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "efficientai.serviceAccountName" . }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.efficientai.worker.pod.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.efficientai.worker.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.efficientai.worker.pod.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.efficientai.worker.pod.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.efficientai.worker.pod.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.efficientai.worker.pod.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker
          image: {{ include "efficientai.image" (dict "root" . "type" "worker") | quote }}
          imagePullPolicy: {{ .Values.efficientai.image.pullPolicy }}
          {{- with .Values.efficientai.worker.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            {{- toYaml .Values.efficientai.worker.command | nindent 12 }}
          env:
            {{- include "efficientai.postgresql.envBlock" . | nindent 12 }}
            {{- include "efficientai.redis.envBlock" . | nindent 12 }}
            {{- include "efficientai.appEnvBlock" . | nindent 12 }}
            {{- with .Values.efficientai.worker.additionalEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/config.yml
              subPath: config.yml
              readOnly: true
            {{- with .Values.efficientai.worker.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.efficientai.worker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "efficientai.fullname" . }}-config
        {{- with .Values.efficientai.worker.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
