{{- if and .Values.efficientai.workerImports.enabled .Values.efficientai.workerImports.autoscaling.enabled (not .Values.efficientai.workerImports.keda.enabled) -}}
{{- $component := "worker-imports" -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "efficientai.componentFullname" (dict "root" . "component" $component) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "efficientai.componentLabels" (dict "root" . "component" $component) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "efficientai.componentFullname" (dict "root" . "component" $component) }}
  minReplicas: {{ .Values.efficientai.workerImports.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.efficientai.workerImports.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.efficientai.workerImports.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.efficientai.workerImports.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
{{- end }}
